version: 2

before:
  hooks:
    - go mod tidy
    - go test -race -count=1 ./...

builds:
  - main: ./cmd/ancc
    binary: ancc
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ .Version }}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

brews:
  - repository:
      owner: ppiankov
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: https://github.com/ppiankov/ancc
    description: Static validator for the Agent-Native CLI Convention
    license: MIT
    install: |
      bin.install "ancc"
    test: |
      system "#{bin}/ancc", "--version"
